parties: # parties default id
  promoter:
    - 10001
  provider:
    - 10002
  arbiter:
    - 10003

backend: 0 # 0 for local, or 1 for spark , or 2 for fc

work_mode: 0 # 0 for standalone, or 1 for cluster

db_type: "LMDB" # LMDB OR CLICKHOUSE OR LFS

data_base_dir: "kernel/examples/data" # path to project base where data is located
